CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "job_applications" (
  "job_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "company" varchar NOT NULL,
  "position" varchar NOT NULL,
  "status" varchar NOT NULL,
  "date_applied" date,
  "notes" text,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "reminders" (
  "reminder_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" integer NOT NULL,
  "reminder_name" varchar NOT NULL,
  "reminder_date" date,
  "description" text,
  "completed" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz DEFAULT (now())
);

ALTER TABLE "job_applications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reminders" ADD FOREIGN KEY ("job_id") REFERENCES "job_applications" ("job_id") DEFERRABLE INITIALLY IMMEDIATE;
